/**
 * Pronunciation Atlas: A mapping of words to their phonetic aliases.
 * This helps Google Cloud TTS handle Sanskrit names and ambiguous English words.
 */
export const PRONUNCIATION_ATLAS: Record<string, string> = {
    // Sanskrit Names - English Male Neural2-B fixes
    'Sumitra': 'Sumitraa',      // Prevents "Sumit" clipping
    'Sumitraa': 'Sumitraa',
    'Vishwamitr': 'Vishwamitra',
    'Vashishth': 'Vashishtha',
    'Dashrath': 'Dashratha',
    'Bharat': 'Bharatha',      // Helps with "T" softness
    'Shatrughan': 'Shatrughna',
    'Janak': 'Janaka',
    'Raavan': 'Raavana',
    'Urmila': 'Urmilaa',
    'Kausalya': 'Kaushalyaa',
    'Kaushalya': 'Kaushalyaa',
    'Kaikeyi': 'Kaikeyee',
    'Ikshvaku': 'Ikshvaaku',
    'Ayodhya': 'Ayodhyaa',
    'Mithila': 'Mithilaa',
    'Rishyashring': 'Rishyashringa',
    'Yagnpurush': 'Yagna purush',
    'Ashwamedh': 'Ashvamedha',
    'Putrakameshti': 'Putra kaameshti',
    'Yagn': 'Yagna',
    'Yagna': 'Yagna',
    'Satyavati': 'Satyavatee',
    'Bhrigu': 'Bhrigoo',

    // Mahabharat Names
    'Mahabharat': 'Mahaabhaarat',
    'Hastinapur': 'Hastinaapuraa',
    'Hastinapura': 'Hastinaapuraa',
    'Kurukshetra': 'Kurukshetra',
    'Pandava': 'Paandava',
    'Kaurava': 'Kauravaa',
    'Kauravas': 'Kauravaas',
    'Yudhishthira': 'Yudhishthiraa',
    'Bhima': 'Bheemaa',
    'Arjuna': 'Arjunaa',
    'Nakula': 'Nakulaa',
    'Sahadeva': 'Sahaadeva',
    'Draupadi': 'Droupadee',
    'Kunti': 'Kuntee',
    'Gandhari': 'Gaandhaaree',
    'Dhritarashtra': 'Dhrutaraashtra',
    'Pandu': 'Paandu',
    'Bhishma': 'Bheeshmaa',
    'Drona': 'Drohnaa',
    'Vidura': 'Viduraa',
    'Karna': 'Karnaa',
    'Satyajit': 'Satyajeet',
    'Janamejaya': 'Janameyajaa',
    'Vyasa': 'Vyaasa',
    'Vaisampayana': 'Vaishampayaana',
    'Sauti': 'Sautee',
    'Naimisharanya': 'Naimishaaranya',
    'Saunaka': 'Shaunakaa',
    'Parashurama': 'Parashuraama',
    'Akshauhini': 'Akshauhinee',
    'Akshauhinis': 'Akshauhinees',
    'Panchala': 'Panchaala',
    'Drupada': 'Dhrupadaa',
    'Swayamvara': 'Swayamvaraa',
    'Ashram': 'Aashram',
    'Yayati': 'Yayaatee',
    'Puru': 'Puruu',
    'Dushmanta': 'Dushmantaa',
    'Shakuntala': 'Shakuntalaa',
    'Bharatavarsha': 'Bharata-varsha',

    // Ambiguous English words in Sanskrit context
    'Sage': 'Sage',            // Forcing English pronunciation, avoids "Sagya"
    'sage': 'sage',
    'Brahmin': 'Braahmin',
    'Kshatriya': 'Kshatreeya',
    'Dharma': 'Dharmaa',
    'Adharma': 'Adharmaa',
    'Karma': 'Karmaa',
};
